# Generated by Django 6.1 on 2026-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contactmessage_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
